service: sls-cost-explorer 

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ap-northeast-1
  environment:
    BUCKET: ${file(./config.json):bucket}
    FONT_NAME: ${file(./config.json):font-name}
    FONT_FAMILY: ${file(./config.json):font-family}
    SLACK_TOKEN: ${file(./.env.json):slack-token}
    SLACK_CHANNEL_ID: ${file(./.env.json):slack-channel}

# you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::"
            - "Ref" : "ServerlessDeploymentBucket"
            - "/*"
    - Effect: "Allow"
      Action:
        - "ce:GetCostAndUsage"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
        - "s3:PutObjectAcl"
        - "s3:GetBucketLocation"
      Resource: 
        Fn::Join : 
          - ""
          - - "arn:aws:s3:::"
            - ${file(./config.json):bucket}
            - "/*"

functions:
  main:
    handler: handler.main
    # The following config will attach a schedule event
    # events:
      # min hour day_of_month month day_of_week year
      # - schedule: cron(0 8 * * ? *)
